<a href="https://colab.research.google.com/github/Akash-Ingle/ComputerVision/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
print(tensor_zero_d.shape)

tf.Tensor(4, shape=(), dtype=int32)
()


In [ ]:
tensor_one_d = tf.constant([1, 2, 3, 4])
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 3],
 [4, 5, 6]],

[[7, 8, 9],
[1, 2, 3]],

[[4, 5, 6],
 [7, 8, 9]],

[[1, 2, 3],
 [4, 5, 6]]
])
print(tensor_three_d)


tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)
print(tensor_three_d.ndim)

(4, 2, 3)
3


In [ ]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np
np_array = np.array([1, 2, 3])
print(np_array)

[1 2 3]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2, 4],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(2, 4, 3, 3), dtype=float32, numpy=
array([[[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]],


       [[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]]], dtype=float32)>

In [ ]:
tf.fill(
    [2,3], 9
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

In [ ]:
# Indexes
tensor_indexed = tf.constant([3, 6, 2, 4, 6, 66, 7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:2])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


In [ ]:
tf.range(2, 5+1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([[1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
# Math Operations
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
x1 = tf.constant([1, 2, 3, 4, 5])
x2 = tf.constant([6, 7, 8, 9, 10])
print(tf.multiply(x1, x2))

tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [ ]:
x1 = tf.constant([1, 2, 3, 4, 5])
x2 = tf.constant([6])
print(tf.add(x1, x2))

tf.Tensor([ 7  8  9 10 11], shape=(5,), dtype=int32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[5.],
       [3.],
       [6.],
       [6.],
       [4.],
       [6.]], dtype=float32)>